# Generated by Django 5.0.14 on 2025-06-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liberta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autoavaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_resposta", models.DateTimeField()),
                ("pontuacao_total", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ComparativoInvestimentoAposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ConteudoApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("tipo", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Depoimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_usuario", models.CharField(max_length=255)),
                ("idade", models.IntegerField()),
                ("texto", models.TextField()),
                ("exibir", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MensagemDoChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                ("data_hora", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PerguntaAutoavaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pergunta", models.TextField()),
                ("tipo_resposta", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Recado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("descricao", models.TextField()),
                ("sentimento", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RespostaAutoavaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resposta", models.TextField()),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liberta.autoavaliacao",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liberta.perguntaautoavaliacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("senha_hash", models.CharField(max_length=255)),
                ("dias_sem_apostar", models.IntegerField()),
                ("data_ultimo_reset", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="AppContent",
        ),
        migrations.DeleteModel(
            name="Diferenca",
        ),
        migrations.DeleteModel(
            name="QuickAccess",
        ),
        migrations.AddField(
            model_name="recado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="liberta.usuario"
            ),
        ),
        migrations.AddField(
            model_name="mensagemdochat",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="liberta.usuario"
            ),
        ),
        migrations.AddField(
            model_name="autoavaliacao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="liberta.usuario"
            ),
        ),
        migrations.DeleteModel(
            name="RecoveryProgress",
        ),
    ]
